export default class Constant {
  // 登陆标题大小
  static readonly LOGIN_SIZE: number = 30
  // 登陆标题颜色
  static readonly LOGIN_COLOR: string = '#2F1155'
  // 输入框长度
  static readonly INPUT_WIDTH: number = 300
  // 输入框高度
  static readonly INPUT_HEIGHT: number = 60
  // 按钮宽度
  static readonly BUTTON_WIDTH: number = 150
  // 按钮高度
  static readonly BUTTON_HEIGHT: number = 50
  // 登陆按钮颜色
  static readonly BUTTON_COLOR: string = '#6E34B8'
  // 标题大小
  static readonly TITLE_SIZE: number = 20
  //space间距
  static readonly SPACE_SIZE: number = 20
  // 过期颜色
  static readonly OVERDUE_COLOR: string = '#FFB1B0'
  // 新鲜颜色
  static readonly FRESH_COLOR: string = '#4EED89'
  // 头像尺寸
  static readonly AVATAR_SIZE: number = 56
  // 输入框图片尺寸
  static readonly INPUT_IMAGE_SIZE: number = 24
}


